root: true
# google style presets
extends: "google"
env:
  node: true
parserOptions:
  ecmaVersion: 7
  sourceType: module
rules:
  no-console: warn
  quotes: [error, single, avoid-escape]
  semi: [error, always]
  no-invalid-this: error
  indent: [warn, 2, { SwitchCase: 1 } ]
  linebreak-style: [warn, unix]
  no-trailing-spaces: warn
  object-curly-spacing: [warn, always]
  max-len: [error, { code: 128, ignoreComments: true }]
  arrow-parens: [error, as-needed]
  no-extra-semi: warn
